FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.ts ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

# Build-time args needed by Next.js for NEXT_PUBLIC_* vars
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

# Generate Prisma client
RUN npx prisma generate

# Build Next.js
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Runtime args — declare and convert to ENV so they survive into the container
ARG DATABASE_URL
ARG AUTH_SECRET
ARG AUTH_URL
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_APP_URL
ARG TOKEN_ENCRYPTION_KEY
ARG META_APP_ID
ARG META_APP_SECRET
ARG META_GRAPH_API_VERSION=v21.0
ARG META_AD_LIBRARY_ENABLED=true
ARG META_AD_LIBRARY_DEFAULT_COUNTRIES=SA,AE,EG,KW,QA
ARG META_SYSTEM_USER_ACCESS_TOKEN
ARG AI_PROVIDER=anthropic
ARG AI_API_KEY
ARG AI_MODEL_TEXT=claude-sonnet-4-6
ARG AI_MODEL_VISION=claude-sonnet-4-6
ARG SMTP_HOST
ARG SMTP_PORT=587
ARG SMTP_USER
ARG SMTP_PASSWORD
ARG SMTP_PASS
ARG SMTP_FROM_EMAIL
ARG SMTP_FROM_NAME
ARG SMTP_FROM
ARG WA_NOTIFICATION_PROVIDER=twilio
ARG WA_TWILIO_ACCOUNT_SID
ARG WA_TWILIO_AUTH_TOKEN
ARG WA_TWILIO_FROM_PHONE
ARG TELEGRAM_ENABLED=false
ARG TELEGRAM_BOT_TOKEN
ARG SHARED_LINK_EXPIRY_DAYS=7
ARG LOG_LEVEL=info
ARG ALERT_CREATIVE_FATIGUE_FREQUENCY=3.0
ARG ALERT_CREATIVE_FATIGUE_CTR_DROP=0.3

ENV DATABASE_URL=$DATABASE_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_URL=$AUTH_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV TOKEN_ENCRYPTION_KEY=$TOKEN_ENCRYPTION_KEY
ENV META_APP_ID=$META_APP_ID
ENV META_APP_SECRET=$META_APP_SECRET
ENV META_GRAPH_API_VERSION=$META_GRAPH_API_VERSION
ENV META_AD_LIBRARY_ENABLED=$META_AD_LIBRARY_ENABLED
ENV META_AD_LIBRARY_DEFAULT_COUNTRIES=$META_AD_LIBRARY_DEFAULT_COUNTRIES
ENV META_SYSTEM_USER_ACCESS_TOKEN=$META_SYSTEM_USER_ACCESS_TOKEN
ENV AI_PROVIDER=$AI_PROVIDER
ENV AI_API_KEY=$AI_API_KEY
ENV AI_MODEL_TEXT=$AI_MODEL_TEXT
ENV AI_MODEL_VISION=$AI_MODEL_VISION
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV SMTP_PASS=$SMTP_PASS
ENV SMTP_FROM_EMAIL=$SMTP_FROM_EMAIL
ENV SMTP_FROM_NAME=$SMTP_FROM_NAME
ENV SMTP_FROM=$SMTP_FROM
ENV WA_NOTIFICATION_PROVIDER=$WA_NOTIFICATION_PROVIDER
ENV WA_TWILIO_ACCOUNT_SID=$WA_TWILIO_ACCOUNT_SID
ENV WA_TWILIO_AUTH_TOKEN=$WA_TWILIO_AUTH_TOKEN
ENV WA_TWILIO_FROM_PHONE=$WA_TWILIO_FROM_PHONE
ENV TELEGRAM_ENABLED=$TELEGRAM_ENABLED
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ENV SHARED_LINK_EXPIRY_DAYS=$SHARED_LINK_EXPIRY_DAYS
ENV LOG_LEVEL=$LOG_LEVEL
ENV ALERT_CREATIVE_FATIGUE_FREQUENCY=$ALERT_CREATIVE_FATIGUE_FREQUENCY
ENV ALERT_CREATIVE_FATIGUE_CTR_DROP=$ALERT_CREATIVE_FATIGUE_CTR_DROP

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
